### ISSUE TITLE
Mediateque not working when port is not 8080

### ISSUE THREAD

**Issue by Fouki** [clementdelestre/TeX#10]
Hello,
When the port of the server is not 8080, the interface is empty. Error message in the web browser is the following :
+1: 
Object { headers: {…}, status: 0, statusText: "Unknown Error", url: "http://192.168.1.168:8080/jsonrpc?request={\"jsonrpc\":\"2.0\",\"id\":\"gettvshows\",\"method\":\"VideoLibrary.GetTvShows\",\"params\":{\"properties\":[\"cast\",\"year\",\"genre\"]}}", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://192.168.1.168:8080/jsonrpc?request={\"jsonrpc\":\"2.0\",\"id\":\"gettvshows\",\"method\":\"VideoLibrary.GetTvShows\",\"params\":{\"properties\":[\"cast\",\"year\",\"genre\"]}}: 0 Unknown Error", error: error

**Comment by clementdelestre** [comment]
Fixed in v1.2.0
