### ISSUE TITLE
Want to add the following features

### ISSUE THREAD

**Issue by serenity666** [clementdelestre/TeX#2]
First of all, thank you very much for developing such an easy-to-use and beautiful plug-in.This is the best Web Interface I've ever used.
But I found some problems in use.
I hope to add more sorting methods, such as year, score and so on.I am a Chinese user. Every word is separate. All Chinese can't be found as easily as letters.
If only I could display the actors, directors, styles and years on the top like music, because I have thousands of movies and sometimes I don't know what to watch, so I can find the movies I want to see faster.
When I click the play button to play a movie, I need to click the play control button in the middle first, and then switch to Kodi to control Kodi. I want me to directly control Kodi after clicking the button.

**Comment by clementdelestre** [comment]
Hi,
I'm glad to see you like it!
I'm already working on a update with some fix and improvements.
It's a lot of work so don't exptect it arrives soon.
I will add a new search page and improve the search experience.
I understand the problem with the player to control Kodi, I will work on this too :)
