### ISSUE TITLE
http port seems hardcoded to 8080

### ISSUE THREAD

**Issue by sgofferj** [clementdelestre/TeX#9]
I have set my kodi port to 80and I TeX doesn't show any content with that. The console is full of 404 errors for "<ip>:8080/jsonrpc". When I set my Kodi web interface port to 8080, TeX works OK.
I'd like to suggest that TeX takes the connect port for the JSON RPC calls from the actual URL instead of always ging for 8080.

**Comment by clementdelestre** [comment]
The port is indeed hardcoded.
I will fix this issue in the next release.
